# Generated by Django 5.0 on 2025-04-07 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Digite o tìtulo', max_length=100, verbose_name='Título')),
                ('pub_date', models.DateField(help_text='Digite a data de publicação', verbose_name='Data de publicação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome da revista', max_length=100, verbose_name='Nome da revista')),
                ('edition', models.IntegerField(help_text='Digite a edição', verbose_name='Edição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome', max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateField()),
                ('cpf', models.CharField(help_text='Digite o CPF', max_length=11, verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome', max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Digite o email', max_length=254, verbose_name='Email')),
                ('cpf', models.CharField(help_text='Digite o CPF', max_length=11, verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagazineArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.article')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.magazine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='magazine',
            name='article',
            field=models.ManyToManyField(blank=True, null=True, through='aula.MagazineArticle', to='aula.article'),
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('number', models.CharField(help_text='Digite o número', max_length=100, verbose_name='Número')),
                ('issue_date', models.DateField(help_text='Digite a data de emissão', verbose_name='Data de emissão')),
                ('expiration_date', models.DateField(help_text='Digite a data de expiração', verbose_name='Data de expiração')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.reporter'),
        ),
    ]
