# Generated by Django 5.0 on 2025-04-20 16:56

import aula.validators.funcoes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(help_text='Digite o CPF', max_length=11, validators=[aula.validators.funcoes.validate_par], verbose_name='CPF'),
        ),
    ]
