# Generated by Django 5.0 on 2025-04-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_alter_person_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='article',
        ),
    ]
