from .base_model import *
from .perfil import *
from .record import *
from .atividade import *
from .clube import *
from .desafio import *
from .equipamento import *
from .desafio_atividades import *
from .desafio_atividades_tempo import *
from .desafio_tempo import *